import type { WorkmanGrammarIr } from "../../../scripts/frontend_v2_grammar_ir.ts";

const constructors: readonly string[] = Object.freeze([
  "ProgramNode<List<SurfaceNode>, Span>",
  "TopPhraseNode<SurfaceNode, SurfaceValue<SurfaceToken>, Span>",
  "ImportDeclarationNode<SurfaceToken, SurfaceNode, SurfaceToken, SurfaceNode, Span>",
  "ImportNamespaceClauseNode<SurfaceToken, SurfaceToken, SurfaceToken, Span>",
  "ImportAllClauseNode<SurfaceToken, Span>",
  "ImportNamedClauseNode<SurfaceToken, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "ImportSpecificationNode<SurfaceToken, Option<SurfaceNode>, Span>",
  "ImportAliasNode<SurfaceToken, SurfaceToken, Span>",
  "JavaScriptImportDeclarationNode<SurfaceToken, SurfaceNode, SurfaceToken, Option<SurfaceToken>, SurfaceNode, Span>",
  "JavaScriptGlobalTargetNode<SurfaceToken, SurfaceValue<SurfaceToken>, SurfaceToken, SurfaceValue<SurfaceToken>, Span>",
  "JavaScriptGlobalRootTargetNode<SurfaceToken, Span>",
  "JavaScriptMetaTargetNode<SurfaceToken, Span>",
  "JavaScriptModuleTargetNode<SurfaceToken, SurfaceValue<SurfaceToken>, SurfaceToken, SurfaceValue<SurfaceToken>, Span>",
  "JavaScriptWorkerTargetNode<SurfaceToken, SurfaceValue<SurfaceToken>, SurfaceToken, SurfaceValue<SurfaceToken>, Span>",
  "JavaScriptImportClauseNode<Option<SurfaceToken>, SurfaceNode, Span>",
  "JavaScriptNamedClauseNode<SurfaceToken, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Option<SurfaceNode>, Span>",
  "JavaScriptImportSpecificationNode<SurfaceToken, Option<SurfaceNode>, Option<SurfaceNode>, Span>",
  "LetDeclarationNode<SurfaceToken, Option<SurfaceToken>, List<SurfaceNode>, List<SurfaceToken>, Span>",
  "LetBindingNode<SurfaceNode, Option<SurfaceNode>, SurfaceValue<SurfaceToken>, SurfaceNode, Span>",
  "RecordDeclarationNode<SurfaceToken, SurfaceToken, Option<SurfaceNode>, SurfaceValue<SurfaceToken>, SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "RecordFieldDeclarationNode<SurfaceToken, SurfaceValue<SurfaceToken>, SurfaceNode, Span>",
  "TypeDeclarationNode<SurfaceToken, SurfaceToken, Option<SurfaceNode>, SurfaceValue<SurfaceToken>, SurfaceNode, Span>",
  "TypeDeclarationBodyNode<Option<SurfaceToken>, List<SurfaceNode>, List<SurfaceToken>, Span>",
  "TypeParametersNode<SurfaceToken, List<SurfaceToken>, SurfaceValue<SurfaceToken>, Span>",
  "NamedTypeNode<SurfaceNode, Option<SurfaceNode>, Span>",
  "TypeVariableNode<SurfaceToken, Span>",
  "FunctionTypeNode<SurfaceNode, SurfaceValue<SurfaceToken>, SurfaceNode, Span>",
  "FunctionTypeDomainNode<Option<SurfaceValue<SurfaceToken>>, List<SurfaceNode>, Option<SurfaceValue<SurfaceToken>>, Span>",
  "GroupedTypeNode<SurfaceValue<SurfaceToken>, SurfaceNode, SurfaceValue<SurfaceToken>, Span>",
  "TupleTypeNode<SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "TypeArgumentsNode<SurfaceToken, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "TypeAnnotationNode<SurfaceValue<SurfaceToken>, SurfaceNode, Span>",
  "NamePatternNode<SurfaceNode, Span>",
  "VariablePatternNode<SurfaceToken, Span>",
  "ExplicitVariablePatternNode<SurfaceToken, SurfaceValue<SurfaceToken>, SurfaceToken, SurfaceValue<SurfaceToken>, Span>",
  "PinnedPatternNode<SurfaceNode, Span>",
  "ConstructorPatternNode<SurfaceNode, Option<SurfaceNode>, Span>",
  "WildcardPatternNode<SurfaceToken, Span>",
  "LiteralPatternNode<SurfaceToken, Span>",
  "TuplePatternNode<SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "ListPatternNode<SurfaceValue<SurfaceToken>, List<SurfaceNode>, Option<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "RecordPatternNode<SurfaceToken, SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "RecordPatternFieldNode<SurfaceToken, Option<SurfaceNode>, Span>",
  "TypedPatternNode<SurfaceNode, SurfaceValue<SurfaceToken>, SurfaceNode, Span>",
  "GroupedPatternNode<SurfaceValue<SurfaceToken>, SurfaceNode, SurfaceValue<SurfaceToken>, Span>",
  "IfExpressionNode<SurfaceToken, SurfaceValue<SurfaceToken>, SurfaceNode, SurfaceValue<SurfaceToken>, SurfaceNode, SurfaceToken, SurfaceNode, Span>",
  "MatchExpressionNode<SurfaceToken, SurfaceValue<SurfaceToken>, SurfaceNode, SurfaceValue<SurfaceToken>, SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "MatchFunctionNode<SurfaceToken, SurfaceValue<SurfaceToken>, List<SurfaceToken>, SurfaceValue<SurfaceToken>, SurfaceValue<SurfaceToken>, SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "MatchArmNode<SurfaceNode, SurfaceValue<SurfaceToken>, SurfaceNode, Span>",
  "LambdaExpressionNode<Option<SurfaceNode>, Option<SurfaceNode>, SurfaceValue<SurfaceToken>, SurfaceNode, Option<SurfaceNode>, Span>",
  "ParametersNode<SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "ParameterNode<SurfaceNode, Option<SurfaceNode>, Span>",
  "DirectiveNode<SurfaceToken, SurfaceToken, SurfaceValue<SurfaceToken>, Span>",
  "BinaryExpressionNode<SurfaceNode, SurfaceToken, SurfaceNode, Span>",
  "UnaryExpressionNode<SurfaceToken, SurfaceNode, Span>",
  "PipeExpressionNode<SurfaceNode, SurfaceToken, SurfaceNode, Span>",
  "PipeMemberNode<SurfaceToken, List<SurfaceToken>, Option<SurfaceNode>, Span>",
  "ApplyExpressionNode<SurfaceNode, SurfaceNode, Span>",
  "AscribedExpressionNode<SurfaceNode, SurfaceValue<SurfaceToken>, SurfaceNode, Span>",
  "ExplicitCallNode<SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "SpaceCallNode<SurfaceNode, Span>",
  "NameExpressionNode<SurfaceNode, Span>",
  "LongNameNode<List<SurfaceToken>, List<SurfaceToken>, Span>",
  "LiteralExpressionNode<SurfaceToken, Span>",
  "PanicExpressionNode<SurfaceToken, SurfaceValue<SurfaceToken>, SurfaceNode, SurfaceValue<SurfaceToken>, Span>",
  "CarrierLiftExpressionNode<SurfaceNode, SurfaceToken, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "LiftTupleExpressionNode<SurfaceToken, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "JsonObjectExpressionNode<SurfaceToken, SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "JsonArrayExpressionNode<SurfaceToken, SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "JsonObjectFieldNode<SurfaceToken, SurfaceValue<SurfaceToken>, SurfaceNode, Span>",
  "RecordExpressionNode<SurfaceToken, SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "NamedRecordExpressionNode<SurfaceNode, SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "RecordFieldNode<SurfaceToken, Option<SurfaceValue<SurfaceToken>>, Option<SurfaceNode>, Span>",
  "RecordSpreadNode<SurfaceToken, SurfaceNode, Span>",
  "ListExpressionNode<SurfaceValue<SurfaceToken>, List<SurfaceNode>, Option<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "TupleExpressionNode<SurfaceValue<SurfaceToken>, List<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "GroupedExpressionNode<SurfaceValue<SurfaceToken>, SurfaceNode, SurfaceValue<SurfaceToken>, Span>",
  "BlockExpressionNode<SurfaceValue<SurfaceToken>, List<SurfaceNode>, Option<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "ParenthesizedSequenceNode<SurfaceValue<SurfaceToken>, List<SurfaceNode>, Option<SurfaceNode>, SurfaceValue<SurfaceToken>, Span>",
  "BlockBodyNode<List<SurfaceNode>, Option<SurfaceNode>, Span>",
  "BlockItemNode<SurfaceNode, SurfaceValue<SurfaceToken>, Span>",
]);

export type SurfaceRuleKind =
  | "node"
  | "custom"
  | "list"
  | "transparent"
  | "token"
  | "trivia"
  | "boundary";

const surfaceRuleGroups: Readonly<Record<SurfaceRuleKind, readonly string[]>> = Object.freeze({
  node: Object.freeze([
    "Start",
    "TopPhrase",
    "ImportDecl",
    "ImportClause",
    "ImportSpec",
    "JsImportDecl",
    "JsTarget",
    "JsImportClause",
    "JsImportClauseBody",
    "JsImportSpec",
    "LetDecl",
    "LetBinding",
    "LetPattern",
    "LetCtorPattern",
    "RecordDecl",
    "RecordFieldDecl",
    "TypeDecl",
    "TypeDeclBody",
    "TypeAnn",
    "IfExpr",
    "MatchExpr",
    "MatchFn",
    "MatchArm",
    "Lambda",
    "LambdaBlock",
    "Directive",
    "Or",
    "And",
    "Equality",
    "Compare",
    "Add",
    "Mul",
    "Unary",
    "Pipe",
    "PipeMember",
    "Postfix",
    "ExplicitCall",
    "SpaceCall",
    "Primary",
    "CarrierLiftTupleExpr",
    "LiftTupleExpr",
    "PanicExpr",
    "JsonExpr",
    "JsonObjectField",
    "RecordExpr",
    "NamedRecordExpr",
    "RecordExprField",
    "ListExpr",
    "TupleOrGroup",
    "ParenSeq",
    "Block",
    "BlockSeqBody",
    "BlockSeqItem",
    "ParenSeqBody",
    "ParenSeqItem",
    "ParamList",
    "Param",
    "Pattern",
    "PatternCore",
    "ParamPattern",
    "CtorPattern",
    "ListPatternItem",
    "ListPattern",
    "ListLetPattern",
    "ListParamPattern",
    "RecordPattern",
    "RecordPatternField",
    "RecordLetPattern",
    "RecordLetPatternField",
    "RecordParamPattern",
    "RecordParamPatternField",
    "FnType",
    "FunctionType",
    "FnTypeDomain",
    "GroupedFunctionType",
    "TypeAtom",
    "TypeParams",
    "LongName",
    "LongConstructor",
  ]),
  custom: Object.freeze([
    "MatchFnParams",
  ]),
  list: Object.freeze([
    "ImportSpecList",
    "JsImportSpecList",
    "LetPatternList",
    "LetCtorPatternList",
    "RecordFieldDeclList",
    "MatchArmList",
    "JsonObjectFieldList",
    "RecordExprFieldList",
    "ParamListItems",
    "ParamPatternList",
    "PatternList",
    "CtorPatternList",
    "ArgList",
    "RecordPatternFieldList",
    "RecordLetPatternFieldList",
    "RecordParamPatternFieldList",
    "TypeList",
  ]),
  transparent: Object.freeze([
    "TopDecl",
    "Expr",
    "LambdaReturnAnnotation",
    "LambdaBody",
    "SpaceArg",
    "BlockDecl",
  ]),
  token: Object.freeze([
    "SemiToken",
    "TypeParam",
    "Float",
    "Int",
    "String",
    "QuotedString",
    "MultilineString",
    "QuotedChar",
    "MultilineChar",
    "LineTerminator",
    "Bool",
    "Void",
    "Wildcard",
    "Identifier",
    "Constructor",
    "Name",
    "MemberName",
    "FieldName",
    "IdentPart",
    "Keyword",
  ]),
  trivia: Object.freeze(["__", "_", "Whitespace", "Comment"]),
  boundary: Object.freeze(["EOF"]),
});

export const surfaceBuilderPlan: Readonly<Record<string, readonly string[]>> = Object.freeze({
  Start: ["ProgramNode"],
  TopPhrase: ["TopPhraseNode"],
  ImportDecl: ["ImportDeclarationNode"],
  ImportClause: [
    "ImportNamespaceClauseNode",
    "ImportAllClauseNode",
    "ImportNamedClauseNode",
  ],
  ImportSpec: ["ImportSpecificationNode"],
  JsImportDecl: ["JavaScriptImportDeclarationNode"],
  JsTarget: [
    "JavaScriptGlobalTargetNode",
    "JavaScriptGlobalRootTargetNode",
    "JavaScriptMetaTargetNode",
    "JavaScriptModuleTargetNode",
    "JavaScriptWorkerTargetNode",
  ],
  JsImportClause: ["JavaScriptImportClauseNode"],
  JsImportClauseBody: [
    "ImportNamespaceClauseNode",
    "JavaScriptNamedClauseNode",
  ],
  JsImportSpec: ["JavaScriptImportSpecificationNode"],
  LetDecl: ["LetDeclarationNode"],
  LetBinding: ["LetBindingNode"],
  LetPattern: [
    "WildcardPatternNode",
    "LiteralPatternNode",
    "RecordPatternNode",
    "ListPatternNode",
    "TuplePatternNode",
    "VariablePatternNode",
    "ExplicitVariablePatternNode",
    "ConstructorPatternNode",
  ],
  LetCtorPattern: [
    "VariablePatternNode",
    "ExplicitVariablePatternNode",
    "ConstructorPatternNode",
    "RecordPatternNode",
    "ListPatternNode",
  ],
  RecordDecl: ["RecordDeclarationNode"],
  RecordFieldDecl: ["RecordFieldDeclarationNode"],
  TypeDecl: ["TypeDeclarationNode"],
  TypeDeclBody: ["TypeDeclarationBodyNode"],
  TypeAnn: ["TypeAnnotationNode"],
  IfExpr: ["IfExpressionNode"],
  MatchExpr: ["MatchExpressionNode"],
  MatchFn: ["MatchFunctionNode"],
  MatchArm: ["MatchArmNode"],
  Lambda: ["LambdaExpressionNode"],
  LambdaBlock: ["BlockExpressionNode"],
  Directive: ["DirectiveNode"],
  Or: ["BinaryExpressionNode"],
  And: ["BinaryExpressionNode"],
  Equality: ["BinaryExpressionNode"],
  Compare: ["BinaryExpressionNode"],
  Add: ["BinaryExpressionNode"],
  Mul: ["BinaryExpressionNode"],
  Unary: ["UnaryExpressionNode"],
  Pipe: ["PipeExpressionNode"],
  PipeMember: ["PipeMemberNode"],
  Postfix: ["ApplyExpressionNode", "AscribedExpressionNode"],
  ExplicitCall: ["ExplicitCallNode"],
  SpaceCall: ["SpaceCallNode"],
  Primary: [
    "LiteralExpressionNode",
    "NameExpressionNode",
    "PanicExpressionNode",
    "CarrierLiftExpressionNode",
    "LiftTupleExpressionNode",
    "JsonObjectExpressionNode",
    "JsonArrayExpressionNode",
    "RecordExpressionNode",
    "NamedRecordExpressionNode",
    "ListExpressionNode",
    "ParenthesizedSequenceNode",
    "TupleExpressionNode",
    "GroupedExpressionNode",
    "BlockExpressionNode",
  ],
  CarrierLiftTupleExpr: ["CarrierLiftExpressionNode"],
  LiftTupleExpr: ["LiftTupleExpressionNode"],
  PanicExpr: ["PanicExpressionNode"],
  JsonExpr: ["JsonObjectExpressionNode", "JsonArrayExpressionNode"],
  JsonObjectField: ["JsonObjectFieldNode"],
  RecordExpr: ["RecordExpressionNode"],
  NamedRecordExpr: ["NamedRecordExpressionNode"],
  RecordExprField: ["RecordSpreadNode", "RecordFieldNode"],
  ListExpr: ["ListExpressionNode"],
  TupleOrGroup: ["TupleExpressionNode", "GroupedExpressionNode"],
  ParenSeq: ["ParenthesizedSequenceNode"],
  Block: ["BlockExpressionNode"],
  BlockSeqBody: ["BlockBodyNode"],
  BlockSeqItem: ["BlockItemNode"],
  ParenSeqBody: ["BlockBodyNode"],
  ParenSeqItem: ["BlockItemNode"],
  ParamList: ["ParametersNode"],
  Param: ["ParameterNode"],
  Pattern: [
    "TypedPatternNode",
    "GroupedPatternNode",
    "WildcardPatternNode",
    "LiteralPatternNode",
    "VariablePatternNode",
    "ExplicitVariablePatternNode",
    "PinnedPatternNode",
    "ConstructorPatternNode",
    "RecordPatternNode",
    "ListPatternNode",
    "TuplePatternNode",
  ],
  PatternCore: [
    "WildcardPatternNode",
    "LiteralPatternNode",
    "VariablePatternNode",
    "ExplicitVariablePatternNode",
    "PinnedPatternNode",
    "ConstructorPatternNode",
    "RecordPatternNode",
    "ListPatternNode",
    "TuplePatternNode",
    "GroupedPatternNode",
  ],
  ParamPattern: [
    "WildcardPatternNode",
    "LiteralPatternNode",
    "VariablePatternNode",
    "ExplicitVariablePatternNode",
  ],
  CtorPattern: [
    "VariablePatternNode",
    "ExplicitVariablePatternNode",
    "ConstructorPatternNode",
    "RecordPatternNode",
    "ListPatternNode",
    "PinnedPatternNode",
  ],
  ListPatternItem: [
    "WildcardPatternNode",
    "LiteralPatternNode",
    "VariablePatternNode",
    "ExplicitVariablePatternNode",
    "ConstructorPatternNode",
    "RecordPatternNode",
    "ListPatternNode",
  ],
  ListPattern: ["ListPatternNode"],
  ListLetPattern: ["ListPatternNode"],
  ListParamPattern: ["ListPatternNode"],
  RecordPattern: ["RecordPatternNode"],
  RecordPatternField: ["RecordPatternFieldNode"],
  RecordLetPattern: ["RecordPatternNode"],
  RecordLetPatternField: ["RecordPatternFieldNode"],
  RecordParamPattern: ["RecordPatternNode"],
  RecordParamPatternField: ["RecordPatternFieldNode"],
  FnType: [
    "FunctionTypeNode",
    "TupleTypeNode",
    "GroupedTypeNode",
    "NamedTypeNode",
    "TypeVariableNode",
  ],
  FunctionType: ["FunctionTypeNode"],
  FnTypeDomain: ["FunctionTypeDomainNode"],
  GroupedFunctionType: ["GroupedTypeNode"],
  TypeAtom: ["TupleTypeNode", "GroupedTypeNode", "NamedTypeNode", "TypeVariableNode"],
  TypeParams: ["TypeParametersNode"],
  LongName: ["LongNameNode"],
  LongConstructor: ["LongNameNode"],
});

export type SurfaceRuleCoverage = Readonly<{
  classified: number;
  missing: readonly string[];
  unknown: readonly string[];
  duplicates: readonly string[];
  missingBuilders: readonly string[];
  unknownConstructors: readonly string[];
}>;

export function surfaceRuleCoverage(grammar: WorkmanGrammarIr): SurfaceRuleCoverage {
  const grammarRules = new Set(grammar.rules.map((rule) => rule.name));
  const seen = new Set<string>();
  const duplicates: string[] = [];
  const unknown: string[] = [];
  for (const names of Object.values(surfaceRuleGroups)) {
    for (const name of names) {
      if (seen.has(name)) duplicates.push(name);
      seen.add(name);
      if (!grammarRules.has(name)) unknown.push(name);
    }
  }
  const nodeRules = new Set(surfaceRuleGroups.node);
  const constructorNames = new Set(
    constructors.map((constructor) => constructor.slice(0, constructor.indexOf("<"))),
  );
  const missingBuilders = [...nodeRules].filter((name) => !(name in surfaceBuilderPlan));
  const unknownConstructors = Object.values(surfaceBuilderPlan)
    .flatMap((names) => names)
    .filter((name) => !constructorNames.has(name));
  return Object.freeze({
    classified: seen.size,
    missing: Object.freeze([...grammarRules].filter((name) => !seen.has(name)).sort()),
    unknown: Object.freeze(unknown.sort()),
    duplicates: Object.freeze(duplicates.sort()),
    missingBuilders: Object.freeze(missingBuilders.sort()),
    unknownConstructors: Object.freeze([...new Set(unknownConstructors)].sort()),
  });
}

export function emitSurfaceTypes(grammar: WorkmanGrammarIr, grammarHash: string): string {
  return [
    "-- Generated by scripts/generate_frontend_v2_recognizer.ts. Do not edit.",
    `-- Grammar: ${grammar.sourcePath}`,
    `-- Grammar IR SHA-256: ${grammarHash}`,
    "-- Formatting-focused Surface AST. It does not reproduce Peggy semantic actions.",
    "",
    "record Span = {",
    "  start: Number,",
    "  end: Number,",
    "};",
    "",
    "record SurfaceComment = {",
    "  text: String,",
    "  span: Span,",
    "};",
    "",
    "record SurfaceToken = {",
    "  kind: String,",
    "  text: String,",
    "  span: Span,",
    "  leadingComments: List<SurfaceComment>,",
    "  recoveryId: Option<Number>,",
    "};",
    "",
    "type SurfaceValue<T> = AuthoredValue<T> | MarkedValue<Number, T>;",
    "type RepairClass = AutoFix | RecoveryOnly;",
    "",
    "record RecoveryMark = {",
    "  id: Number,",
    "  anchor: Number,",
    "  expectedText: String,",
    "  rule: String,",
    "  repairClass: RepairClass,",
    "};",
    "",
    "type SurfaceNode =",
    ...constructors.map((constructor, index) =>
      `  ${index === 0 ? "| " : "| "}${constructor}${index === constructors.length - 1 ? ";" : ""}`
    ),
    "",
    "record SurfaceProgram = {",
    "  root: SurfaceNode,",
    "  marks: List<RecoveryMark>,",
    "  preamble: String,",
    "};",
    "",
  ].join("\n");
}

export function emitSurfaceRuleMetadata(
  grammar: WorkmanGrammarIr,
  grammarHash: string,
): string {
  return [
    "-- Generated by scripts/generate_frontend_v2_recognizer.ts. Do not edit.",
    `-- Grammar: ${grammar.sourcePath}`,
    `-- Grammar IR SHA-256: ${grammarHash}`,
    "-- Mechanical rule classifications consumed by Surface construction.",
    "",
    emitRuleMatcher(
      "isTriviaRule",
      [...surfaceRuleGroups.trivia, ...surfaceRuleGroups.boundary],
    ),
    "",
    emitRuleMatcher("isTokenRule", surfaceRuleGroups.token),
    "",
    emitRuleMatcher("isListRule", surfaceRuleGroups.list),
    "",
    emitRuleMatcher("isTransparentRule", surfaceRuleGroups.transparent),
    "",
  ].join("\n");
}

function emitRuleMatcher(name: string, rules: readonly string[]): string {
  return [
    `let ${name} = match(name) => {`,
    ...rules.map((rule) => `  ${JSON.stringify(rule)} => { true },`),
    "  _ => { false },",
    "};",
  ].join("\n");
}

export function surfaceConstructorCount(): number {
  return constructors.length;
}
