import { compileLibraryFile } from "../src/compiler.ts";
import { fileURLToPath } from "node:url";

const source = fileURLToPath(new URL("../tooling/tuiman/diagnostic.wm", import.meta.url));
const output = new URL("../src/generated/tuiman.js", import.meta.url);

const generated = [
  "// Generated by scripts/build_tuiman.ts. Do not edit by hand.",
  await compileLibraryFile(source, { frontend: "v2" }),
].join("\n");

// Compilation completes before the previous stage-0 artifact is replaced.
const current = await Deno.readTextFile(output).catch((error) => {
  if (error instanceof Deno.errors.NotFound) return undefined;
  throw error;
});
if (current !== generated) await Deno.writeTextFile(output, generated);
