import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const root = fileURLToPath(new URL("../", import.meta.url));
const zig = Deno.env.get("WM_ZIG_PATH") ?? "zig";
const environment = await new Deno.Command(zig, { args: ["env"], stdout: "piped", stderr: "piped" })
  .output();
if (!environment.success) throw new Error(new TextDecoder().decode(environment.stderr));
const zon = new TextDecoder().decode(environment.stdout);
function field(name: string): string {
  const value = zon.match(new RegExp("[.]" + name + ' = (".*")'))?.[1];
  if (!value) throw new Error(`zig env is missing ${name}`);
  return JSON.parse(value);
}
if (field("version") !== "0.16.0") {
  throw new Error("Build the pinned Aro extractor with Zig 0.16.0");
}
const aro = join(field("lib_dir"), "compiler", "aro");
const directory = join(root, "tooling", "c-header-extractor", "dist");
const generated = join(root, "src", "generated", "c_header_extractor");
const platforms = [
  ["linux-x64", "x86_64-linux-musl"],
  ["linux-arm64", "aarch64-linux-musl"],
  ["darwin-x64", "x86_64-macos"],
  ["darwin-arm64", "aarch64-macos"],
  ["win32-x64", "x86_64-windows"],
  ["win32-arm64", "aarch64-windows"],
];
const hash = (bytes: Uint8Array | string) => createHash("sha256").update(bytes).digest("hex");
await fs.mkdir(directory, { recursive: true });
await fs.mkdir(generated, { recursive: true });
const resources: Record<string, string> = {};
async function collect(source: string, prefix: string) {
  for (
    const entry of (await fs.readdir(source, { withFileTypes: true })).sort((a, b) =>
      a.name.localeCompare(b.name)
    )
  ) {
    const path = join(source, entry.name);
    const key = `${prefix}/${entry.name}`;
    if (entry.isDirectory()) await collect(path, key);
    else if (entry.isFile()) resources[key] = await fs.readFile(path, "utf8");
  }
}
await collect(join(aro, "include"), "include");
await collect(join(root, "tooling", "c-header-extractor", "licenses"), "licenses");
resources.LICENSE = await fs.readFile(join(dirname(field("lib_dir")), "LICENSE"), "utf8");
resources.NOTICE = await fs.readFile(join(root, "tooling", "c-header-extractor", "NOTICE"), "utf8");
const resourcesJson = JSON.stringify(resources);
await fs.writeFile(
  join(generated, "resources.js"),
  `// Generated by scripts/build_c_header_extractor.ts.\nexport const resources = ${resourcesJson};\n`,
);
const sourceHash = hash(await fs.readFile(join(root, "tooling", "c-header-extractor", "main.zig")));
for (const [platform, target] of platforms) {
  const output = join(directory, platform);
  await fs.mkdir(output, { recursive: true });
  const name = platform.startsWith("win32-")
    ? "workman-c-header-extractor.exe"
    : "workman-c-header-extractor";
  const binary = join(output, name);
  console.log(`Building Aro extractor for ${platform} (${target})`);
  const result = await new Deno.Command(zig, {
    args: [
      "build-exe",
      "-O",
      "ReleaseSafe",
      "-fstrip",
      "-target",
      target,
      "--dep",
      "aro",
      `-Mroot=${join(root, "tooling", "c-header-extractor", "main.zig")}`,
      `-Maro=${join(aro, "aro.zig")}`,
      `-femit-bin=${binary}`,
    ],
    stdout: "inherit",
    stderr: "inherit",
  }).output();
  if (!result.success) throw new Error(`Aro extractor build failed for ${platform}`);
  for (const [path, contents] of Object.entries(resources)) {
    await fs.mkdir(dirname(join(output, path)), { recursive: true });
    await fs.writeFile(join(output, path), contents);
  }
  const bytes = await fs.readFile(binary);
  const manifest = {
    protocol: 1,
    zigBuildVersion: "0.16.0",
    platform,
    target,
    executable: name,
    sha256: hash(bytes),
    resourcesSha256: hash(resourcesJson),
    sourceSha256: sourceHash,
  };
  await fs.writeFile(join(output, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  const payload = { ...manifest, gzipBase64: gzipSync(bytes, { level: 9 }).toString("base64") };
  await fs.writeFile(
    join(generated, `${platform}.js`),
    `// Generated by scripts/build_c_header_extractor.ts.\nexport const asset = ${
      JSON.stringify(payload)
    };\n`,
  );
  console.log(`Built ${platform}: ${bytes.length} bytes (${payload.gzipBase64.length} encoded)`);
}
console.log("Generated bundled C header extractors for all six platforms");
