import { build, stop } from "npm:esbuild@0.25.12";
import { fileURLToPath } from "node:url";

// Standalone emitted programs cannot depend on the compiler's installation path.
// Bundle the complete vendored API into a self-contained module for C codecs.
try {
  const result = await build({
    entryPoints: [fileURLToPath(new URL("../src/vendor/byte_type/mod.ts", import.meta.url))],
    bundle: true,
    write: false,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    minify: true,
    charset: "ascii",
    legalComments: "none",
  });
  const license = await Deno.readTextFile(
    new URL("../src/vendor/byte_type/LICENSE", import.meta.url),
  );
  const source = `/*\n${license.trim()}\n*/\n${result.outputFiles![0].text}`;
  const url = `data:text/javascript,${encodeURIComponent(source)}`;
  const output = "// Generated by scripts/build_byte_type.ts. Do not edit by hand.\n" +
    "// deno-fmt-ignore-file\n" +
    `export const byteTypeRuntimeUrl = ${JSON.stringify(url)};\n`;
  const outputUrl = new URL("../src/generated/byte_type_runtime.ts", import.meta.url);
  if (Deno.args.includes("--check")) {
    if (await Deno.readTextFile(outputUrl) !== output) {
      throw new Error("byte_type runtime is stale; run deno task byte-type:build");
    }
  } else if (await Deno.readTextFile(outputUrl).catch(() => undefined) !== output) {
    await Deno.writeTextFile(outputUrl, output);
  }
} finally {
  stop();
}
