import { compileFile } from "../src/compiler.ts";

const source = new URL("../tooling/problems/app.wm", import.meta.url).pathname;
const output = new URL("../src/generated/problems_tui.mjs", import.meta.url);
const generated = [
  "// Generated by scripts/build_problems_tui.ts. Do not edit by hand.",
  await compileFile(source, { frontend: "v2" }),
].join("\n");

const current = await Deno.readTextFile(output).catch((error) => {
  if (error instanceof Deno.errors.NotFound) return undefined;
  throw error;
});
if (current !== generated) await Deno.writeTextFile(output, generated);
