import { compileLibraryFile } from "../src/compiler.ts";
import { fileURLToPath } from "node:url";

const source = fileURLToPath(new URL("../tooling/problems/app.wm", import.meta.url));
const output = new URL("../src/generated/problems_tui.js", import.meta.url);
const generated = [
  "// Generated by scripts/build_problems_tui.ts. Do not edit by hand.",
  await compileLibraryFile(source, { frontend: "v2" }),
].join("\n");

const current = await Deno.readTextFile(output).catch((error) => {
  if (error instanceof Deno.errors.NotFound) return undefined;
  throw error;
});
if (current !== generated) await Deno.writeTextFile(output, generated);
