import peggy from "peggy";

type Asset = {
  name: string;
  url: URL;
};

const assets: Asset[] = [
  { name: "listSource", url: new URL("../std/list.wm", import.meta.url) },
  { name: "mapSource", url: new URL("../std/map.wm", import.meta.url) },
  { name: "monadSource", url: new URL("../std/monad.wm", import.meta.url) },
  { name: "optionSource", url: new URL("../std/option.wm", import.meta.url) },
  { name: "resultSource", url: new URL("../std/result.wm", import.meta.url) },
  { name: "taskSource", url: new URL("../std/task.wm", import.meta.url) },
  { name: "traverseSource", url: new URL("../std/traverse.wm", import.meta.url) },
];

const outputUrl = new URL("../src/generated/assets.ts", import.meta.url);
const declarations = await Promise.all(
  assets.map(async ({ name, url }) => {
    // Keep generated output identical across Windows and Unix checkouts, even
    // when an editor writes an input asset with CRLF line endings.
    const source = (await Deno.readTextFile(url)).replace(/\r\n?/g, "\n");
    return `export const ${name} = ${JSON.stringify(source)};`;
  }),
);
const output = [
  "// Generated by scripts/generate_assets.ts. Do not edit by hand.",
  "// deno-fmt-ignore-file",
  "",
  ...declarations,
  "",
].join("\n");

await Deno.mkdir(new URL("./", outputUrl), { recursive: true });
const current = await Deno.readTextFile(outputUrl).catch((error) => {
  if (error instanceof Deno.errors.NotFound) return undefined;
  throw error;
});
if (current !== output) await Deno.writeTextFile(outputUrl, output);

await Promise.all([
  generateParser(
    new URL("../src/grammar.peggy", import.meta.url),
    new URL("../src/generated/workman_parser.js", import.meta.url),
  ),
  generateParser(
    new URL("../src/grammar.wmsml.peggy", import.meta.url),
    new URL("../src/generated/wmsml_parser.js", import.meta.url),
  ),
]);

async function generateParser(grammarUrl: URL, parserUrl: URL): Promise<void> {
  const grammar = (await Deno.readTextFile(grammarUrl)).replace(/\r\n?/g, "\n");
  const source = peggy.generate(grammar, {
    output: "source",
    format: "es",
    cache: true,
  }) as string;
  const generated = [
    "// Generated by scripts/generate_assets.ts. Do not edit by hand.",
    source,
    "",
  ].join("\n");
  const current = await Deno.readTextFile(parserUrl).catch((error) => {
    if (error instanceof Deno.errors.NotFound) return undefined;
    throw error;
  });
  if (current !== generated) await Deno.writeTextFile(parserUrl, generated);
}
