type Asset = {
  name: string;
  url: URL;
};

const assets: Asset[] = [
  { name: "workmanGrammar", url: new URL("../src/grammar.peggy", import.meta.url) },
  { name: "wmsmlGrammar", url: new URL("../src/grammar.wmsml.peggy", import.meta.url) },
  { name: "listSource", url: new URL("../std/list.wm", import.meta.url) },
  { name: "monadSource", url: new URL("../std/monad.wm", import.meta.url) },
  { name: "optionSource", url: new URL("../std/option.wm", import.meta.url) },
  { name: "resultSource", url: new URL("../std/result.wm", import.meta.url) },
  { name: "taskSource", url: new URL("../std/task.wm", import.meta.url) },
];

const outputUrl = new URL("../src/generated/assets.ts", import.meta.url);
const declarations = await Promise.all(
  assets.map(async ({ name, url }) => {
    // Keep generated output identical across Windows and Unix checkouts, even
    // when an editor writes an input asset with CRLF line endings.
    const source = (await Deno.readTextFile(url)).replace(/\r\n?/g, "\n");
    return `export const ${name} = ${JSON.stringify(source)};`;
  }),
);
const output = [
  "// Generated by scripts/generate_assets.ts. Do not edit by hand.",
  "// deno-fmt-ignore-file",
  "",
  ...declarations,
  "",
].join("\n");

await Deno.mkdir(new URL("./", outputUrl), { recursive: true });
const current = await Deno.readTextFile(outputUrl).catch((error) => {
  if (error instanceof Deno.errors.NotFound) return undefined;
  throw error;
});
if (current !== output) await Deno.writeTextFile(outputUrl, output);
