import peggy from "peggy";

/**
 * Library directories whose top-level `.wm` files are compiled into the default basis, and whose
 * `js/` subdirectory holds the JavaScript primitives those modules import. Every file is discovered,
 * so adding a library module or primitive file never requires editing this script.
 */
const libraryDirectories = ["basis", "std", "host/js"];

const repositoryUrl = new URL("../", import.meta.url);
const outputUrl = new URL("../src/generated/assets.ts", import.meta.url);
const libraryPaths = (await Promise.all(
  libraryDirectories.map((directory) => filePaths(directory, ".wm")),
)).flat().sort();
const libraryJsPaths = (await Promise.all(
  libraryDirectories.map((directory) => filePaths(`${directory}/js`, ".js")),
)).flat().sort();
const output = [
  "// Generated by scripts/generate_assets.ts. Do not edit by hand.",
  "// deno-fmt-ignore-file",
  "",
  "/** Library module sources keyed by repository-relative path, in path order. */",
  "export const librarySources: Readonly<Record<string, string>> = {",
  ...await sourceEntries(libraryPaths),
  "};",
  "",
  "/** JavaScript primitive files of the library modules, keyed by repository-relative path. */",
  "export const libraryJsSources: Readonly<Record<string, string>> = {",
  ...await sourceEntries(libraryJsPaths),
  "};",
  "",
].join("\n");

await Deno.mkdir(new URL("./", outputUrl), { recursive: true });
const current = await Deno.readTextFile(outputUrl).catch((error) => {
  if (error instanceof Deno.errors.NotFound) return undefined;
  throw error;
});
if (current !== output) await Deno.writeTextFile(outputUrl, output);

await Promise.all([
  generateParser(
    new URL("../src/grammar.wmsml.peggy", import.meta.url),
    new URL("../src/generated/wmsml_parser.js", import.meta.url),
  ),
]);

function sourceEntries(paths: string[]): Promise<string[]> {
  return Promise.all(paths.map(async (path) => {
    // Keep generated output identical across Windows and Unix checkouts, even
    // when an editor writes an input asset with CRLF line endings.
    const source = (await Deno.readTextFile(new URL(path, repositoryUrl))).replace(/\r\n?/g, "\n");
    return `  ${JSON.stringify(path)}: ${JSON.stringify(source)},`;
  }));
}

/** Files of one directory with the given extension; a missing directory contributes nothing. */
async function filePaths(directory: string, extension: string): Promise<string[]> {
  const paths: string[] = [];
  try {
    for await (const entry of Deno.readDir(new URL(`${directory}/`, repositoryUrl))) {
      if (entry.isFile && entry.name.endsWith(extension)) paths.push(`${directory}/${entry.name}`);
    }
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }
  return paths;
}

async function generateParser(
  grammarUrl: URL,
  parserUrl: URL,
): Promise<void> {
  const grammar = (await Deno.readTextFile(grammarUrl)).replace(/\r\n?/g, "\n");
  const source = peggy.generate(grammar, {
    output: "source",
    format: "es",
    cache: true,
  }) as string;
  const generated = [
    "// Generated by scripts/generate_assets.ts. Do not edit by hand.",
    source,
    "",
  ].join("\n");
  const current = await Deno.readTextFile(parserUrl).catch((error) => {
    if (error instanceof Deno.errors.NotFound) return undefined;
    throw error;
  });
  if (current !== generated) await Deno.writeTextFile(parserUrl, generated);
}
