#!/usr/bin/env -S deno run --allow-read --allow-write --allow-env

type Options = {
  binDir: string;
  force: boolean;
};

const repoRoot = pathFromFileUrl(new URL("..", import.meta.url));

async function main(args: string[]): Promise<number> {
  const options = parseArgs(args);
  if (!options) return 2;

  await Deno.mkdir(options.binDir, { recursive: true });

  const target = join(options.binDir, "wm");
  const existing = await readIfExists(target);
  if (existing && !options.force && !existing.includes("wm-mini installer")) {
    console.error(`refusing to overwrite existing ${target}`);
    console.error("rerun with --force to replace it");
    return 1;
  }

  await Deno.writeTextFile(target, launcherScript(repoRoot));
  await Deno.chmod(target, 0o755);

  console.log(`installed wm -> ${target}`);
  console.log(`launcher target: ${join(repoRoot, "src/main.ts")}`);
  return 0;
}

function parseArgs(args: string[]): Options | undefined {
  let binDir = defaultBinDir();
  let force = false;

  for (let index = 0; index < args.length; index++) {
    const arg = args[index];
    if (arg === "--help" || arg === "-h") {
      usage();
      return undefined;
    }
    if (arg === "--force") {
      force = true;
      continue;
    }
    if (arg === "--bin-dir") {
      binDir = requireValue(args, ++index, arg);
      continue;
    }
    if (arg.startsWith("--bin-dir=")) {
      binDir = arg.slice("--bin-dir=".length);
      continue;
    }
    if (arg === "--prefix") {
      binDir = join(requireValue(args, ++index, arg), "bin");
      continue;
    }
    if (arg.startsWith("--prefix=")) {
      binDir = join(arg.slice("--prefix=".length), "bin");
      continue;
    }
    console.error(`unknown argument: ${arg}`);
    usage();
    return undefined;
  }

  return { binDir: expandHome(binDir), force };
}

function defaultBinDir(): string {
  return Deno.env.get("WM_INSTALL_BIN_DIR") ?? "~/.local/bin";
}

function requireValue(args: string[], index: number, flag: string): string {
  const value = args[index];
  if (!value) throw new Error(`${flag} requires a value`);
  return value;
}

function expandHome(path: string): string {
  if (path === "~") return Deno.env.get("HOME") ?? path;
  if (path.startsWith("~/")) return join(Deno.env.get("HOME") ?? "~", path.slice(2));
  return path;
}

async function readIfExists(path: string): Promise<string | undefined> {
  try {
    return await Deno.readTextFile(path);
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return undefined;
    throw error;
  }
}

function launcherScript(root: string): string {
  const main = join(root, "src/main.ts");
  return `#!/usr/bin/env sh
# generated by wm-mini installer
exec deno run -A ${shellQuote(main)} "$@"
`;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function join(...parts: string[]): string {
  const [first = "", ...rest] = parts;
  return rest.reduce((path, part) => {
    const left = path.endsWith("/") ? path.slice(0, -1) : path;
    const right = part.startsWith("/") ? part.slice(1) : part;
    return `${left}/${right}`;
  }, first);
}

function pathFromFileUrl(url: URL): string {
  return decodeURIComponent(url.pathname).replace(/\/$/, "");
}

function usage() {
  console.error(`usage: deno run --allow-read --allow-write --allow-env scripts/install.ts [options]

options:
  --bin-dir DIR   install wm directly into DIR
  --prefix DIR    install wm into DIR/bin
  --force         overwrite an existing non-wm-mini launcher

default:
  ~/.local/bin, or WM_INSTALL_BIN_DIR if set
`);
}

if (import.meta.main) {
  Deno.exit(await main(Deno.args));
}
